### ISSUE TITLE
PIN code can simply be bypassed on SDK 23

### ISSUE THREAD

**Issue by callmemagnus** [andOTP/andOTP#159]
#### General information

* **App version:** 0.5.0
* **App source:** F-Droid* 
* **Android Version:** SDK 23
* **Custom ROM:** no

#### Expected result
**What is expected?** PIN code to block the view of the OTPs

**What does happen instead?** App crashes and the restarts by showing the OTPs.

#### Logcat
```
03-17 16:37:28.359 5469-5469/org.shadowice.flocke.andotp.dev E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: org.shadowice.flocke.andotp.dev, PID: 5469
                                                                               java.lang.IllegalArgumentException: password empty
                                                                                   at com.android.org.bouncycastle.jcajce.provider.digest.SHA1$BasePBKDF2WithHmacSHA1.engineGenerateSecret(SHA1.java:135)
                                                                                   at javax.crypto.SecretKeyFactory.generateSecret(SecretKeyFactory.java:187)
                                                                                   at org.shadowice.flocke.andotp.Utilities.EncryptionHelper.generatePBKDF2Credentials(EncryptionHelper.java:77)
                                                                                   at org.shadowice.flocke.andotp.Activities.AuthenticateActivity.checkPassword(AuthenticateActivity.java:145)
                                                                                   at org.shadowice.flocke.andotp.Activities.AuthenticateActivity.onClick(AuthenticateActivity.java:129)
                                                                                   at android.view.View.performClick(View.java:5198)
                                                                                   at android.view.View$PerformClick.run(View.java:21147)
                                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

#### Steps to reproduce
 
1. open the app
2. tap unlock
3. see the app crash
4. tap ok -> app reloads without requesting the PIN code

**Comment by flocke** [comment]
Just tested on my device (SDK 27) and it works there. Must be something with lower SDKs. I will check out your fix tomorrow, thanks.
