### ISSUE TITLE
Crash at startup after app update

### ISSUE THREAD

**Issue by KnightOfCups** [andOTP/andOTP#188]
#### General information

* **App version:** 0.6.0-beta1
* **App source:** F-Droid 1.2.2
* **Android Version:** 4.4.4
* **Custom ROM:** Lineage OS 11-20170417-UNOFFICAL

#### Expected result
**What does happen instead?**
The app has been updated from 0.5.0.1 to 0.6.0-beta1 then crashed at first use after.
It seems to have an inconsistency between my data and what is expected by the new version: if the app is reset by clearing the data, the app does not crash at startup and I get the wizard.
Unfortunately if I restore my previous data from a backup, then the app crashed again at startup or I get a message for KeyStore loading failure. After switching to Password / PIN  in settings, I can't find my previous OTP.

#### Logcat
```
I/GeofencerStateMachine( 6387): removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_ALL packageName=org.shadowice.flocke.andotp]
E/NfcHelper( 9071): android.content.pm.PackageManager$NameNotFoundException: org.shadowice.flocke.andotp
D/VoicemailCleanupService(13449): Cleaning up data for package: org.shadowice.flocke.andotp
I/GrowthService(13166): Package org.shadowice.flocke.andotp uninstalled. Removing from storage.
D/InstalledAppProviderSer( 9071): deleteAppFromDb org.shadowice.flocke.andotp
I/LocationSettingsChecker(13166): Removing dialog suppression flag for package org.shadowice.flocke.andotp
I/Icing   (13166): doRemovePackageData org.shadowice.flocke.andotp
E/WorkSourceUtil(13166): Could not find package: org.shadowice.flocke.andotp
I/Icing   (13166): doRemovePackageData org.shadowice.flocke.andotp
I/PackageManager(  553): Running dexopt on: org.shadowice.flocke.andotp
D/Launcher.Model( 8860): shortcutWasRestored is false for org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity
I/ChromeSync(13166): [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.shadowice.flocke.andotp flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
I/FontsPackageChangeOp(13166): Package org.shadowice.flocke.andotp has no metadata
D/InstalledAppProviderSer( 9071): insertAppIntoDb org.shadowice.flocke.andotp
I/Timeline( 8860): Timeline: Activity_launch_request id:org.shadowice.flocke.andotp time:5008024
D/dalvikvm(14002): Process 14002 nice name: org.shadowice.flocke.andotp
D/ActivityThread(14002): handleBindApplication:org.shadowice.flocke.andotp
I/dalvikvm(14002): Could not find method android.app.KeyguardManager.createConfirmDeviceCredentialIntent, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.authenticate
I/dalvikvm(14002): Could not find method org.shadowice.flocke.andotp.Activities.MainActivity.finishAndRemoveTask, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult
W/dalvikvm(14002): VFY: unable to resolve virtual method 27361: Lorg/shadowice/flocke/andotp/Activities/MainActivity;.finishAndRemoveTask ()V
I/dalvikvm(14002): Could not find method android.content.res.Configuration.getLocales, referenced from method org.shadowice.flocke.andotp.Utilities.Tools.getSystemLocale
E/dalvikvm(14002): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair
W/dalvikvm(14002): VFY: unable to resolve new-instance 354 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;
D/dalvikvm(14002): DexOpt: unable to opt direct call 0x0736 at 0x29 in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;.loadOrGenerateAsymmetricKeyPair
I/ActivityManager(  553): Displayed org.shadowice.flocke.andotp/.Activities.MainActivity: +2s413ms
I/Timeline(  553): Timeline: Activity_windows_visible id: ActivityRecord{22042ea4 u0 org.shadowice.flocke.andotp/.Activities.MainActivity t30} time:5010560
W/System.err(14002): java.io.FileNotFoundException: /data/data/org.shadowice.flocke.andotp/files/secrets.dat: open failed: ENOENT (No such file or directory)
W/System.err(14002): 	at org.shadowice.flocke.andotp.Utilities.FileHelper.readFileToBytes(FileHelper.java:78)
W/System.err(14002): 	at org.shadowice.flocke.andotp.Utilities.DatabaseHelper.loadDatabase(DatabaseHelper.java:122)
W/System.err(14002): 	at org.shadowice.flocke.andotp.View.EntriesCardAdapter.loadEntries(EntriesCardAdapter.java:135)
W/System.err(14002): 	at org.shadowice.flocke.andotp.Activities.MainActivity.populateAdapter(MainActivity.java:185)
W/System.err(14002): 	at org.shadowice.flocke.andotp.Activities.MainActivity.updateEncryption(MainActivity.java:425)
W/System.err(14002): 	at org.shadowice.flocke.andotp.Activities.MainActivity.access$000(MainActivity.java:80)
W/System.err(14002): 	at org.shadowice.flocke.andotp.Activities.MainActivity$3.onClick(MainActivity.java:117)
W/InputDispatcher(  553): channel '224ea924 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  553): channel '224ea924 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
W/InputDispatcher(  553): Attempted to unregister already unregistered input channel '224ea924 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity (server)'
I/oandbackup(14034): restoring: andOTP
I/Timeline( 8860): Timeline: Activity_launch_request id:org.shadowice.flocke.andotp time:5076842
D/dalvikvm(14218): Process 14218 nice name: org.shadowice.flocke.andotp
D/ActivityThread(14218): handleBindApplication:org.shadowice.flocke.andotp
I/dalvikvm(14218): Could not find method android.app.KeyguardManager.createConfirmDeviceCredentialIntent, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.authenticate
I/dalvikvm(14218): Could not find method org.shadowice.flocke.andotp.Activities.MainActivity.finishAndRemoveTask, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult
W/dalvikvm(14218): VFY: unable to resolve virtual method 27361: Lorg/shadowice/flocke/andotp/Activities/MainActivity;.finishAndRemoveTask ()V
I/dalvikvm(14218): Could not find method android.content.res.Configuration.getLocales, referenced from method org.shadowice.flocke.andotp.Utilities.Tools.getSystemLocale
E/dalvikvm(14218): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair
W/dalvikvm(14218): VFY: unable to resolve new-instance 354 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;
D/dalvikvm(14218): DexOpt: unable to opt direct call 0x0736 at 0x29 in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;.loadOrGenerateAsymmetricKeyPair
D/dalvikvm(14248): Process 14248 nice name: org.shadowice.flocke.andotp
D/ActivityThread(14248): handleBindApplication:org.shadowice.flocke.andotp
I/dalvikvm(14248): Could not find method android.app.KeyguardManager.createConfirmDeviceCredentialIntent, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.authenticate
I/dalvikvm(14248): Could not find method org.shadowice.flocke.andotp.Activities.MainActivity.finishAndRemoveTask, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult
W/dalvikvm(14248): VFY: unable to resolve virtual method 27361: Lorg/shadowice/flocke/andotp/Activities/MainActivity;.finishAndRemoveTask ()V
I/dalvikvm(14248): Could not find method android.content.res.Configuration.getLocales, referenced from method org.shadowice.flocke.andotp.Utilities.Tools.getSystemLocale
E/dalvikvm(14248): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair
W/dalvikvm(14248): VFY: unable to resolve new-instance 354 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;
D/dalvikvm(14248): DexOpt: unable to opt direct call 0x0736 at 0x29 in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;.loadOrGenerateAsymmetricKeyPair
I/Timeline( 8860): Timeline: Activity_launch_request id:org.shadowice.flocke.andotp time:5687861
I/ActivityManager(  553): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.shadowice.flocke.andotp/.Activities.MainActivity} from pid 8860
D/dalvikvm(15124): Process 15124 nice name: org.shadowice.flocke.andotp
I/ActivityManager(  553): Start proc org.shadowice.flocke.andotp for activity org.shadowice.flocke.andotp/.Activities.MainActivity: pid=15124 uid=10182 gids={50182, 1028, 1015, 1023, 1006}
D/ActivityThread(15124): handleBindApplication:org.shadowice.flocke.andotp
I/dalvikvm(15124): Could not find method android.app.KeyguardManager.createConfirmDeviceCredentialIntent, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.authenticate
I/dalvikvm(15124): Could not find method org.shadowice.flocke.andotp.Activities.MainActivity.finishAndRemoveTask, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult
W/dalvikvm(15124): VFY: unable to resolve virtual method 27361: Lorg/shadowice/flocke/andotp/Activities/MainActivity;.finishAndRemoveTask ()V
I/dalvikvm(15124): Could not find method android.content.res.Configuration.getLocales, referenced from method org.shadowice.flocke.andotp.Utilities.Tools.getSystemLocale
E/dalvikvm(15124): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair
W/dalvikvm(15124): VFY: unable to resolve new-instance 354 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;
D/dalvikvm(15124): DexOpt: unable to opt direct call 0x0736 at 0x29 in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;.loadOrGenerateAsymmetricKeyPair
E/AndroidRuntime(15124): Process: org.shadowice.flocke.andotp, PID: 15124
E/AndroidRuntime(15124): java.lang.RuntimeException: Unable to resume activity {org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}: java.lang.IllegalArgumentException: key.length == 0
E/AndroidRuntime(15124): 	at org.shadowice.flocke.andotp.Utilities.SecretKeyWrapper.unwrap(SecretKeyWrapper.java:79)
E/AndroidRuntime(15124): 	at org.shadowice.flocke.andotp.Utilities.EncryptionHelper.loadOrGenerateWrappedKey(EncryptionHelper.java:177)
E/AndroidRuntime(15124): 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadEncryptionKeyFromKeyStore(KeyStoreHelper.java:113)
E/AndroidRuntime(15124): 	at org.shadowice.flocke.andotp.Activities.MainActivity.updateEncryption(MainActivity.java:413)
E/AndroidRuntime(15124): 	at org.shadowice.flocke.andotp.Activities.MainActivity.onResume(MainActivity.java:324)
W/ActivityManager(  553):   Force finishing activity org.shadowice.flocke.andotp/.Activities.MainActivity
I/WindowManager(  553): Screenshot max retries 4 of Token{225a5860 ActivityRecord{2200ec78 u0 org.shadowice.flocke.andotp/.Activities.MainActivity t36 f}} appWin=Window{21e46244 u0 Starting org.shadowice.flocke.andotp} drawState=4
W/ActivityManager(  553): Activity pause timeout for ActivityRecord{2200ec78 u0 org.shadowice.flocke.andotp/.Activities.MainActivity t36 f}
I/ActivityManager(  553): Process org.shadowice.flocke.andotp (pid 15124) has died.
I/ActivityManager(  553): START u0 {act=android.settings.APPLICATION_DETAILS_SETTINGS dat=package:org.shadowice.flocke.andotp flg=0x10808000 cmp=com.android.settings/.applications.InstalledAppDetails} from pid 8860
I/InstalledAppDetails(15377): Clearing user data for package : org.shadowice.flocke.andotp
I/ActivityManager(  553): Force stopping org.shadowice.flocke.andotp appid=10182 user=0: clear data
I/GeofencerStateMachine( 6387): removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_ALL packageName=org.shadowice.flocke.andotp]
I/LocationSettingsChecker(14164): Removing dialog suppression flag for package org.shadowice.flocke.andotp
I/InstalledAppDetails(15377): Cleared user data for package : org.shadowice.flocke.andotp
I/Icing   (14164): doRemovePackageData org.shadowice.flocke.andotp
I/ActivityManager(  553): START u0 {act=android.intent.action.UNINSTALL_PACKAGE dat=package:org.shadowice.flocke.andotp cmp=com.android.packageinstaller/.UninstallerActivity (has extras)} from pid 15377
I/ActivityManager(  553): Force stopping org.shadowice.flocke.andotp appid=10182 user=-1: uninstall pkg
W/PackageManager(  553): Couldn't delete native library directory /data/app-lib/org.shadowice.flocke.andotp
I/ActivityManager(  553): Force stopping org.shadowice.flocke.andotp appid=10182 user=0: pkg removed
D/BackupManagerService(  553): Received broadcast Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:org.shadowice.flocke.andotp flg=0x4000010 (has extras) }
I/GeofencerStateMachine( 6387): removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_ALL packageName=org.shadowice.flocke.andotp]
E/InstalledAppDetails(15377): Exception when retrieving package:org.shadowice.flocke.andotp
E/InstalledAppDetails(15377): android.content.pm.PackageManager$NameNotFoundException: org.shadowice.flocke.andotp
W/AppSecurityPermissions(15377): Couldn't retrieve permissions for package:org.shadowice.flocke.andotp
D/VoicemailCleanupService(14349): Cleaning up data for package: org.shadowice.flocke.andotp
I/GrowthService(14164): Package org.shadowice.flocke.andotp uninstalled. Removing from storage.
I/LocationSettingsChecker(14164): Removing dialog suppression flag for package org.shadowice.flocke.andotp
I/Icing   (14164): doRemovePackageData org.shadowice.flocke.andotp
I/AppUpdateStatusService(15677): org.shadowice.flocke.andotp:16 is NOT pending install, probably just left over from a previous install.
I/AppUpdateStatusService(15677): org.shadowice.flocke.andotp:14 is NOT pending install, probably just left over from a previous install.
D/InstalledAppProviderSer(15677): deleteAppFromDb org.shadowice.flocke.andotp
D/InstalledAppProviderSer(15677): deleteAppFromDb org.shadowice.flocke.andotp
W/ActivityManager(  553): No content provider found for permission revoke: file:///storage/sdcard1/oandbackups/org.shadowice.flocke.andotp/org.shadowice.flocke.andotp-2.apk
I/PackageManager(  553): Verification timed out for file:///storage/sdcard1/oandbackups/org.shadowice.flocke.andotp/org.shadowice.flocke.andotp-2.apk
I/PackageManager(  553): Continuing with installation of file:///storage/sdcard1/oandbackups/org.shadowice.flocke.andotp/org.shadowice.flocke.andotp-2.apk
W/ActivityManager(  553): No content provider found for permission revoke: file:///storage/sdcard1/oandbackups/org.shadowice.flocke.andotp/org.shadowice.flocke.andotp-2.apk
I/PackageManager(  553): Running dexopt on: org.shadowice.flocke.andotp
I/ActivityManager(  553): Force stopping org.shadowice.flocke.andotp appid=10185 user=-1: update pkg
D/BackupManagerService(  553): Received broadcast Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.shadowice.flocke.andotp flg=0x4000010 (has extras) }
I/BackupManagerService(  553): Scheduling backup for new app org.shadowice.flocke.andotp
D/BackupManagerService(  553): Now staging backup of org.shadowice.flocke.andotp
D/Launcher.Model( 8860): shortcutWasRestored is false for org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity
I/oandbackup(14034): restoring: andOTP
I/ChromeSync(14164): [Sync,SyncIntentOperation] Handling the intent: Intent { act=android.intent.action.PACKAGE_ADDED dat=package:org.shadowice.flocke.andotp flg=0x4000010 cmp=com.google.android.gms/.chimera.GmsIntentOperationService (has extras) }.
I/FontsPackageChangeOp(14164): Package org.shadowice.flocke.andotp has no metadata
D/InstalledAppProviderSer(15677): insertAppIntoDb org.shadowice.flocke.andotp
I/Timeline( 8860): Timeline: Activity_launch_request id:org.shadowice.flocke.andotp time:6023930
I/ActivityManager(  553): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.shadowice.flocke.andotp/.Activities.MainActivity} from pid 8860
D/dalvikvm(16062): Process 16062 nice name: org.shadowice.flocke.andotp
I/ActivityManager(  553): Start proc org.shadowice.flocke.andotp for activity org.shadowice.flocke.andotp/.Activities.MainActivity: pid=16062 uid=10185 gids={50185, 1028, 1015, 1023, 1006}
D/ActivityThread(16062): handleBindApplication:org.shadowice.flocke.andotp
I/dalvikvm(16062): Could not find method android.app.KeyguardManager.createConfirmDeviceCredentialIntent, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.authenticate
I/dalvikvm(16062): Could not find method org.shadowice.flocke.andotp.Activities.MainActivity.finishAndRemoveTask, referenced from method org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult
W/dalvikvm(16062): VFY: unable to resolve virtual method 30808: Lorg/shadowice/flocke/andotp/Activities/MainActivity;.finishAndRemoveTask ()V
I/dalvikvm(16062): Could not find method android.content.res.Configuration.getLocales, referenced from method org.shadowice.flocke.andotp.Utilities.Tools.getSystemLocale
W/System.err(16062): 	at org.shadowice.flocke.andotp.Activities.MainActivity.onCreate(MainActivity.java:172)
E/dalvikvm(16062): Could not find class 'android.app.NotificationChannel', referenced from method org.shadowice.flocke.andotp.Utilities.NotificationHelper.createNotificationChannel
W/dalvikvm(16062): VFY: unable to resolve new-instance 56 (Landroid/app/NotificationChannel;) in Lorg/shadowice/flocke/andotp/Utilities/NotificationHelper;
D/dalvikvm(16062): DexOpt: unable to opt direct call 0x016f at 0x14 in Lorg/shadowice/flocke/andotp/Utilities/NotificationHelper;.createNotificationChannel
E/dalvikvm(16062): Could not find class 'android.security.keystore.KeyGenParameterSpec$Builder', referenced from method org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadOrGenerateAsymmetricKeyPair
W/dalvikvm(16062): VFY: unable to resolve new-instance 555 (Landroid/security/keystore/KeyGenParameterSpec$Builder;) in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;
D/dalvikvm(16062): DexOpt: unable to opt direct call 0x0aa1 at 0x29 in Lorg/shadowice/flocke/andotp/Utilities/KeyStoreHelper;.loadOrGenerateAsymmetricKeyPair
W/System.err(16062): 	at org.shadowice.flocke.andotp.Utilities.SecretKeyWrapper.unwrap(SecretKeyWrapper.java:80)
W/System.err(16062): 	at org.shadowice.flocke.andotp.Utilities.EncryptionHelper.loadOrGenerateWrappedKey(EncryptionHelper.java:177)
W/System.err(16062): 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadEncryptionKeyFromKeyStore(KeyStoreHelper.java:113)
W/System.err(16062): 	at org.shadowice.flocke.andotp.Activities.MainActivity.updateEncryption(MainActivity.java:398)
W/System.err(16062): 	at org.shadowice.flocke.andotp.Activities.MainActivity.onResume(MainActivity.java:304)
E/AndroidRuntime(16062): Process: org.shadowice.flocke.andotp, PID: 16062
W/ActivityManager(  553):   Force finishing activity org.shadowice.flocke.andotp/.Activities.MainActivity
I/WindowManager(  553): Screenshot max retries 4 of Token{22496c0c ActivityRecord{222affec u0 org.shadowice.flocke.andotp/.Activities.MainActivity t38 f}} appWin=Window{22424d34 u0 Starting org.shadowice.flocke.andotp} drawState=4
W/ActivityManager(  553): Activity pause timeout for ActivityRecord{222affec u0 org.shadowice.flocke.andotp/.Activities.MainActivity t38 f}
I/ActivityManager(  553): Process org.shadowice.flocke.andotp (pid 16062) has died.
I/WindowState(  553): WIN DEATH: Window{2232ca0c u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}
I/WindowState(  553): WIN DEATH: Window{21ed0e40 u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}
```

**Comment by flocke** [comment]
Does it work if you clear the apps data, set it up fresh with Password / PIN encryption and then import your old backup?

**Comment by flocke** [comment]
Closing due to missing information / response.
