### ISSUE TITLE
Cannot restore encrypted backup

### ISSUE THREAD

**Issue by noctrex** [andOTP/andOTP#376]
Unfortunately it seems that I cannot restore my encrypted file backup.
I've also tried with a second smartphone, and cannot succeed either.

Just tried a fresh install of the lastest andOTP from FDroid, used pin for authentication and database encryption. 
Added a simple password but with a special char for the backup password.
Added a new OTP,
Proceed to take an backup (encrypted), and try to restore it again, and it fails. The file is stored on my Google Drive and it seems that it gets corrupted somehow.

**Comment by flocke** [comment]
Do you export it directly to Google drive from andOTP? If yes that could be the problem, try saving it locally on you phone first and then uploading it.

**Comment by noctrex** [comment]
> 
> 
> Do you export it directly to Google drive from andOTP? If yes that could be the problem, try saving it locally on you phone first and then uploading it.

Yes, I did it directly. If done locally first, the file can be restored. But my problem is that I've got a backup saved directly and cannot restore it now. So I guess I've lost it, or is there a possibility to recover from this?

**Comment by flocke** [comment]
Sadly it is probably lost for good, what is the size of the file you are trying to restore?
The strange thing is that in most cases it is not zero, so something is written to the file, just not the correct stuff.

**Comment by noctrex** [comment]
> Sadly it is probably lost for good, what is the size of the file you are trying to restore?
> The strange thing is that in most cases it is not zero, so something is written to the file, just not the correct stuff.

my file saved on drive is "otp_accounts_2019-07-17_16-21-48.json.aes" and its 4107 bytes.
I've even tried with the script from asmw/andOTP-decrypt but it wont decrypt either.

**Comment by flocke** [comment]
I'm currently on vacation, so I can't really look into it. Could you try saving the same backup locally and to the drive and compare the sizes? Maybe you could take a logcat, if you know how to, of you trying to save to drive directly and post it here.

**Comment by noctrex** [comment]
Well, that's the problem, that was my backup. I've reformatted the phone and tried to restore it, so I've lost my OTP's

**Comment by flocke** [comment]
I have a new debug build where I changed some stuff regarding the export of the backups.
In that new build exporting and importing directly to and from Google Drive and other cloud providers should work (I tested it on my phone with Nextcloud and Google Drive).
If you want you can download and try it [here](https://cloud.shadowice.org/s/Q96sGRHsrAiKC33). It will install as a new app (called "andOTP (dev)") so it does not interfere with your existing installation.

**Comment by luger19** [comment]
I have the same problem: I exported a backup to the cloud. AndOTP told me to use a new encryption method which I did. Under "Backup" and "Restore" was also "Restore old backup" (where you could use the deprecated method again for old backups). So I uninstalled andOTP and reinstalled it to see if I could import the backup again, which didn't work (although I saved the file locally). By the way, the third option in the settings with the old encryption method was no longer visible, although it was the latest andOTP version (according to F-Droid).

**Comment by flocke** [comment]
@luger19 The new encryption method is currently only available in the beta, which is not yet on F-Droid. You will need the beta again if you want to restore the backup.

**Comment by luger19** [comment]
@flocke thanks, now with the Google Play beta version again, it works

**Comment by vdrandom** [comment]
Having the same issue: tried to backup my andOTP on one phone and restore on another, black screen on file choice, no opts imported. Even with the beta version. Funny thing, I've chosen andOTP becuase of this feature specifically. :D 

Thankfully, no data lost, the app on the old phone works fine so far.

**Comment by flocke** [comment]
Strange, please make sure you are using the correct import option and password on your second phone. If you use a version lower than 0.6.3 on the old phone you need to use the legacy import on the new one.

Also, did you set the backup globaly in the settings before importing? If yes try removing it (simply setting it to an empty value) and importing again, in that case you should get asked for the password after the file selection.

**Comment by flocke** [comment]
And, what do you mean with "black screen on role choice"? Do you mean you select a file and afterwards it goes black or does it go black instead of letting you select a file?

**Comment by vdrandom** [comment]
Never mind, apparently my old phone decided it doesn't want to let me get the damn file via mtp, I ended up trying to load a very old backup, probably made a year ago.

Yeah, I select a file and then after a short wait app's part of the screen goes black (standard android panels aside, that is). A few seconds later app just crashes.

I've transferred the proper backup via other methods and everything imported fine.

**Comment by vdrandom** [comment]
The password was set globally (on both old and new phones).

**Comment by flocke** [comment]
Yeah, if something happens during the file transfer it is going to fail. Because of that reason I am thinking about adding some kind of integrity check to the import and export. Maybe just creating a second file with the MD5 sum of the backup on export and, if both files are present during import, matching the MD5 sum to verify the file.

**Comment by vdrandom** [comment]
Maybe embed checksum into some kind of header withtin the file? (Although it would probably make the file harder to work with via external tools like openssl / text editors in case one would want to extract the data.)

**Comment by flocke** [comment]
Yeah, I'm probably gonna extend the backup format in the future to include some kind of header. Right now it is just a binary blob that is encrypted with AES256. Maybe I will use some kind of JSON wrapper in the future that just included the encrypted database as Base32 or Base64 encoded data.

**Comment by flocke** [comment]
Closing since the original issue is most likely a problem with the Documents Provider (Google Drive, Nextcloud, ...) and not with andOTP itself. If something like this still occurs after the 0.8.0 release (which reworks a lot of the storage code) please just reopen.

**Comment by omegasupreme3** [comment]
I would like to reopen this bug.

I see the same behavior occur for version 0.8.0. I actually never tried to restore a backup, so I didn't notice it is broken (?) . I made an encrypted backup on my phone (Pixel 4a) using local storage and tried to restore it on a Samsung Galaxy Tab 4. This fails. I also created an unencrypted backup, but that one fails to restore as well. For the latter one I can confirm it actually contains valid data.

Is it possible for you to re-investigate this issue?

**Comment by flocke** [comment]
@omegasupreme3 Could you try to capture a log while trying to restore the unencrypted backup?

I use the backup function a lot (mostly unenecrypted for testing and with OpenPGP on my main device) and never encountered this problem so I can't really debug it myself.

**Comment by omegasupreme3** [comment]
Sure! I checked the settings, but I don't see an option to capture a log. Did I miss something?

**Comment by flocke** [comment]
> Sure! I checked the settings, but I don't see an option to capture a log. Did I miss something?

It's not in the apps settings, it's an Android function: https://wiki.lineageos.org/how-to/logcat

**Comment by omegasupreme3** [comment]
Ah ok, that's familiar. I did a capture and checked the log. The only thing that seems interesting to me is an exception being thrown from AndOTP:

`04-14 20:51:33.580 29933 29933 W System.err: java.io.FileNotFoundException: /data/user/0/org.shadowice.flocke.andotp/files/secrets.dat: open failed: ENOENT (No such file or directory)
04-14 20:51:33.580 29933 29933 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:496)
04-14 20:51:33.580 29933 29933 W System.err: 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
04-14 20:51:33.580 29933 29933 W System.err: 	at org.shadowice.flocke.andotp.Utilities.FileHelper.readFileToBytes(FileHelper.java:35)
04-14 20:51:33.580 29933 29933 W System.err: 	at org.shadowice.flocke.andotp.Utilities.DatabaseHelper.loadDatabase(DatabaseHelper.java:130)
04-14 20:51:33.580 29933 29933 W System.err: 	at org.shadowice.flocke.andotp.View.EntriesCardAdapter.loadEntries(EntriesCardAdapter.java:199)
04-14 20:51:33.580 29933 29933 W System.err: 	at org.shadowice.flocke.andotp.Activities.MainActivity.populateAdapter(MainActivity.java:166)
04-14 20:51:33.580 29933 29933 W System.err: 	at org.shadowice.flocke.andotp.Activities.MainActivity.onResume(MainActivity.java:379)
04-14 20:51:33.580 29933 29933 W System.err: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1454)
04-14 20:51:33.580 29933 29933 W System.err: 	at android.app.Activity.performResume(Activity.java:8105)
04-14 20:51:33.580 29933 29933 W System.err: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4616)
04-14 20:51:33.580 29933 29933 W System.err: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4659)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.os.Looper.loop(Looper.java:237)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
04-14 20:51:33.581 29933 29933 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-14 20:51:33.581 29933 29933 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-14 20:51:33.581 29933 29933 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-14 20:51:33.581 29933 29933 W System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
04-14 20:51:33.581 29933 29933 W System.err: 	at libcore.io.Linux.open(Native Method)
04-14 20:51:33.581 29933 29933 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-14 20:51:33.581 29933 29933 W System.err: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
04-14 20:51:33.581 29933 29933 W System.err: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
04-14 20:51:33.581 29933 29933 W System.err: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7984)
04-14 20:51:33.581 29933 29933 W System.err: 	at libcore.io.IoBridge.open(IoBridge.java:482)`

Does this ring a bell for you?

**Comment by omegasupreme3** [comment]
Is there any way I can provide you more valuable information with?

**Comment by flocke** [comment]
Could you maybe provide the full log?

The error you posted is common and should be no problem. It happens when you first start the app and have not yet added any accounts. I should probably just silence it to avoid confusion.

**Comment by omegasupreme3** [comment]
This actually happened with an existing AndOTP installation and containing entries. I will create a new log and post it fully.

**Comment by omegasupreme3** [comment]
So I started debugging myself figuring I could find the issue faster. Upon selecting the backup I noticed it was slightly smaller than it should be, so I figured the file is possibly corrupt as it cannot be parsed correctly. When trying to import an older (or newly created) version of the backup up, importing just works fine. How could it be possible that the backup was corrupted? This is what you really **don't** want to happen ... After all you create a backup so your data is save. Did you (or could you) implement some kind of flow where the backup would be verified after it was made?

**Comment by flocke** [comment]
In the latest version of andOTP the backups should be far more reliable, but an integrity check might still be a good idea.

**Comment by omegasupreme3** [comment]
Thanks that would be very welcome indeed.

**Comment by flocke** [comment]
I won't be able to add the verification for version 0.9.0 (which is already in beta so I won't be adding new features). But it should make it into 0.9.1.

**Comment by omegasupreme3** [comment]
That is understandable. I am happy that you are willing to implement this anyway!

**Comment by IzzySoft** [comment]
Just wondering: can the aes file be decrypted on the Linux command line? What cipher would be needed to specify there? Like in:

    openssl enc -d -aes-256-cbc -in otp_accounts.json.aes -out otp_accounts.json

I couldn't find any cipher with AES256 and SHA in the supported list.

**Comment by flocke** [comment]
@IzzySoft The backups use a custom file format, so you won't be able to decrypt them with `openssl`. But there are some tools available to do this. For the Linux command line I would suggest this Python script: https://github.com/asmw/andOTP-decrypt

**Comment by IzzySoft** [comment]
Thanks @flocke – that sounds awesome! Even able to create scanable QR codes. A good fallback (and option for those who (no idea why) would want to switch to a different OTP app. Blind me, you've even linked that from the Readme… :see_no_evil:

**Comment by DavidCPlatt** [comment]
I'm not sure if it's the same problem, but I've found it impossible to completely restore a PGP-encrypted backup.

I made a backup on my phone (two keys), encrypted with my usual PGP key.

If I export it to my Linux desktop, I can decrypt it and I see reasonable-looking JSON.

If I transfer it to another phone and try restoring it into a (blank) andOTP, the restore appears to hang, with the progress indicator spinning.

If I force-quit the app and re-launch it, I find that the first key was restored, but the second is absent.

This has happened on two different devices I've tried to import the file into, running very different versions of Android.

Version 0.9.0-1, using OpenKeychain as the key provider.
