### ISSUE TITLE
Crash when clicking away BitWarden safe dialog

### ISSUE THREAD

**Issue by SuperSandro2000** [andOTP/andOTP#406]
#### General information

* **App version:** 0.6.3.1-play
* **App source:** Google Play / F-Droid / GitHub / ... Google Play
* **Android Version:** 9
* **Custom ROM:** ThouchWiz

#### Expected result
**What is expected?**
no crash

**What does happen instead?** 
crash

#### Logcat
```
10-23 15:08:53.556 E/AndroidRuntime(19809): Process: org.shadowice.flocke.andotp, PID: 19809
10-23 15:08:53.556 E/AndroidRuntime(19809): 	at org.shadowice.flocke.andotp.View.EntriesCardAdapter.updateLastUsed(EntriesCardAdapter.java:348)
10-23 15:08:53.556 E/AndroidRuntime(19809): 	at org.shadowice.flocke.andotp.View.EntriesCardAdapter.hideEntry(EntriesCardAdapter.java:291)
10-23 15:08:53.556 E/AndroidRuntime(19809): 	at org.shadowice.flocke.andotp.View.EntriesCardAdapter.access$800(EntriesCardAdapter.java:74)
10-23 15:08:53.556 E/AndroidRuntime(19809): 	at org.shadowice.flocke.andotp.View.EntriesCardAdapter$1$1.run(EntriesCardAdapter.java:245)
```

#### Steps to reproduce
 
* open app
* enter pin
* click somewhere except on the BitWarden safe dialog
* andOTP crashes

**Comment by ziegenberg** [comment]
Can this be reproduced?
