### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by dennisguse** [andOTP/andOTP#631]
#### General information

* **App version:** 0.8.0-beta
* **App source:** F-Droid
* **Android Version:** 10
* **Custom ROM:** LineageOS

#### Expected result
**What is expected?** 

App works :)

**What does happen instead?**

App crashes.

#### Logcat
```
2020-08-16 18:46:52.826 17102-17102/org.shadowice.flocke.andotp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.shadowice.flocke.andotp, PID: 17102
    java.lang.ArrayIndexOutOfBoundsException: length=7; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at org.shadowice.flocke.andotp.View.EntriesCardAdapter.cardTapToRevealHandler(EntriesCardAdapter.java:372)
        at org.shadowice.flocke.andotp.View.EntriesCardAdapter.access$400(EntriesCardAdapter.java:84)
        at org.shadowice.flocke.andotp.View.EntriesCardAdapter$1.onCardSingleClicked(EntriesCardAdapter.java:319)
        at org.shadowice.flocke.andotp.View.EntryViewHolder$5.onSingleClick(EntryViewHolder.java:147)
        at org.shadowice.flocke.andotp.View.SimpleDoubleClickListener$1.run(SimpleDoubleClickListener.java:50)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

#### Steps to reproduce
 
 * tap a TOTP multiple times (reveal, unreveal); quickly after another

**Comment by flocke** [comment]
Fixed by #634

**Comment by dennisguse** [comment]
Nice! 
Can we get this fix released soonish?
I tend to trigger this behavior at least once a week.

**Comment by flocke** [comment]
I will try to release a new beta version later today. If no new bugs are reported during the next week I'm going to release the stable version next weekend.
