### ISSUE TITLE
Crash when modifying other settings after changing backup location

### ISSUE THREAD

**Issue by jsoberg** [andOTP/andOTP#639]
#### General information

* **App version:** master
* **App source:** GitHub
* **Android Version:** 29
* **Custom ROM:** None (x86 Emulator)

#### Steps to reproduce

1. Open andOTP.
1. Open Settings.
1. Scroll down and select "Default backup location" preference.
1. Select a new default backup location and allow.
1. Select some other preference (e.g. "Verify encrypted backups")

#### Expected result
**What is expected?** 
Preference is selected normally.

**What does happen instead?**
App crashes from a null Context.

#### Logcat
```
2020-09-04 15:06:48.935 14076-14076/org.shadowice.flocke.andotp.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.shadowice.flocke.andotp.dev, PID: 14076
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
        at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:555)
        at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:545)
        at org.shadowice.flocke.andotp.Utilities.Settings.<init>(Settings.java:59)
        at org.shadowice.flocke.andotp.Utilities.BackupHelper.autoBackupType(BackupHelper.java:91)
        at org.shadowice.flocke.andotp.Activities.SettingsActivity$SettingsFragment.updateAutoBackup(SettingsActivity.java:317)
        at org.shadowice.flocke.andotp.Activities.SettingsActivity.onSharedPreferenceChanged(SettingsActivity.java:171)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
        at android.preference.Preference.tryCommit(Preference.java:1621)
        at android.preference.Preference.persistBoolean(Preference.java:1925)
        at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:89)
        at android.preference.TwoStatePreference.onClick(TwoStatePreference.java:74)
        at android.preference.Preference.performClick(Preference.java:1163)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:260)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
        at android.widget.AbsListView$3.run(AbsListView.java:4097)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by jsoberg** [comment]
[PR 640](https://github.com/andOTP/andOTP/pull/640) ready for this ticket
