### ISSUE TITLE
No backup file created

### ISSUE THREAD

**Issue by rexxmundi** [andOTP/andOTP#677]
* **App version:** 0.7.1.1-play
* **App source:** Google Play
* **Android Version:** 10 
* **Custom ROM:** Lineageos 17.1 

#### Expected result
After selecting backup function, backup file is created.   

Selected backup function and toast says "backup to external storage successful", however no backup file appears in the location defined in settings (/storage/emulated/0/andOTP).  Tried manually setting alternate backup location but no file appears.  andOTP has storage permissions.

#### Logcat
[10-22 20:17:23.059 2003:2003 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: org.shadowice.flocke.andotp, PID: 2003
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=binary/aes (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5168)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.showSaveFileSelector(BackupActivity.java:373)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.saveFileWithPermissions(BackupActivity.java:398)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.access$200(BackupActivity.java:72)
	at org.shadowice.flocke.andotp.Activities.BackupActivity$3.onClick(BackupActivity.java:140)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

[10-22 20:17:43.678 2007:2007 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: org.shadowice.flocke.andotp, PID: 2007
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=binary/aes (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5168)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.showSaveFileSelector(BackupActivity.java:373)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.saveFileWithPermissions(BackupActivity.java:398)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.access$200(BackupActivity.java:72)
	at org.shadowice.flocke.andotp.Activities.BackupActivity$3.onClick(BackupActivity.java:140)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

[10-22 20:17:53.158 2010:2010 E/AndroidRuntime]
FATAL EXCEPTION: main
Process: org.shadowice.flocke.andotp, PID: 2010
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=binary/aes (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2058)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1716)
	at android.app.Activity.startActivityForResult(Activity.java:5210)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
	at android.app.Activity.startActivityForResult(Activity.java:5168)
	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.showSaveFileSelector(BackupActivity.java:373)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.saveFileWithPermissions(BackupActivity.java:398)
	at org.shadowice.flocke.andotp.Activities.BackupActivity.access$200(BackupActivity.java:72)
	at org.shadowice.flocke.andotp.Activities.BackupActivity$3.onClick(BackupActivity.java:140)
	at android.view.View.performClick(View.java:7259)
	at android.view.View.performClickInternal(View.java:7236)
	at android.view.View.access$3600(View.java:801)
	at android.view.View$PerformClick.run(View.java:27892)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

[10-22 20:18:06.475 2014:2014 E/AndroidRuntime]

#### Steps to reproduce
1. Burger
2. Backup
3. Backup (encrypted)

**Comment by rozmansi** [comment]
Workaround: Enable Settings >> Backup >> Ask for filename

**Comment by rexxmundi** [comment]
> Workaround: Settings >> Backup >> enable Ask for filename

Hello rozmansi,

Thanks for the work around, but it did not produce a different outcome.  LogCat as follows:

[logcat_10-27-2020_21-38-00.txt](https://github.com/andOTP/andOTP/files/5445671/logcat_10-27-2020_21-38-00.txt)

**Comment by flocke** [comment]
You don't seem to have an app that can handle the CREATE_DOCUMENT intent. Usually every ROM should include one, especially on Android 10 since this is the only way to create files on external storage on Android 10+. Did you disable the default Documents app on LineageOS?

**Comment by rexxmundi** [comment]
Hello flocke,

Thanks for the feedback.  I cannot seem to find the default Documents app in the drawer so that might very well be the problem (nor can I find it in a list of disabled apps)

Don't suppose that you would have any suggestions about what app in Google Play would be able to catch the intents?

Regards,
Rex

**Comment by rexxmundi** [comment]
Hello flocke,

Thanks for the feedback, you are spot on.  I had disabled 'Files' after installing CX File Explorer thinking that this was a drop in replacement.

Sent you a development contribution via Paypal for your excellent software and support.

Regards,
Mike
