### ISSUE TITLE
App Crashes When Tapping On Scan QR Code

### ISSUE THREAD

**Issue by TakuyaSama** [andOTP/andOTP#806]
#### General information

* **App version:** 0.9.0-beta1
* **App source:** GitHub
* **Android Version:** 11
* **Custom ROM:** LineageOS 18.1

#### Expected result
**What is expected?**
The app launches the QR Scanning normally. 

**What does happen instead?**
The app crashes just after tapping on "Scan QR Code".

#### Logcat
https://pastebin.com/7QLKWKab

#### Steps to reproduce
 
 * Launch andOTP.
 * Tap on the "+" button.
 * Tap on the "Scan QR Code" option.
 * Experiment the crash.

**Comment by ziegenberg** [comment]
Can be reproduced on other phones with Android 11. Might be related to the following log lines.

```
FATAL EXCEPTION: main
Process: org.shadowice.flocke.andotp, PID: 11594
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.SecureCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.WindowInsetsController com.android.internal.policy.DecorView.getWindowInsetsController()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7660)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.WindowInsetsController com.android.internal.policy.DecorView.getWindowInsetsController()' on a null object reference
	at com.android.internal.policy.PhoneWindow.getInsetsController(PhoneWindow.java:3880)
	at org.shadowice.flocke.andotp.Activities.SecureCaptureActivity.initializeContent(SecureCaptureActivity.java:29)
	at com.journeyapps.barcodescanner.CaptureActivity.onCreate(CaptureActivity.java:21)
	at android.app.Activity.performCreate(Activity.java:8000)
	at android.app.Activity.performCreate(Activity.java:7984)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
	... 11 more
```

**Comment by ziegenberg** [comment]
I've added a potential fix for this bug. @flocke can you test this?
