### ISSUE TITLE
Cloud provider as backup target

### ISSUE THREAD

**Issue by nursoda** [andOTP/andOTP#810]
I'd like to make sure I always have a recent backup saved safely in case there's something wrong with my phone.

I'd like to be able to select e.g. Nextcloud as storage provider to save the (automatically) saved backup files to.

**Comment by flocke** [comment]
This is already possible. I am using it with Nextcloud as default provider currently.

**Comment by nursoda** [comment]
OK, Sorry! So this is a support issue. So if I should be able to select a cloud provider instead of a local file I will check app open defaults.

**Comment by flocke** [comment]
Yes, that error should be fixed in the next release.

If you don't see Nextcloud as option in the file manager then that is also the reason why you can't use it in andOTP. Sadly I have no idea why it wouldn't show up, maybe the devs of the Nextcloud Android app can help you with that.

**Comment by pschichtel** [comment]
I've been using Nextcloud as a target for OpenGPG encrypted backups for ages on my old phone, with my new phone it stopped working: https://github.com/nextcloud/android/issues/4219

Not sure if this is a Nextcloud or AndOTP issue:

```05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: Download of filepath to /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/tmp/some/filepath: Unexpected exception
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: android.os.NetworkOnMainThreadException
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1605)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.google.android.gms.org.conscrypt.Platform.blockGuardOnNetwork(:com.google.android.gms@211515046@21.15.15 (150400-371058782):0)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@211515046@21.15.15 (150400-371058782):2)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:248)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:267)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.isStale(HttpConnection.java:506)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpConnection.closeIfStale(HttpConnection.java:431)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.closeIfStale(MultiThreadedHttpConnectionManager.java:1313)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:382)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:219)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.downloadFile(DownloadFileRemoteOperation.java:111)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.resources.files.DownloadFileRemoteOperation.run(DownloadFileRemoteOperation.java:88)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.operations.DownloadFileOperation.run(DownloadFileOperation.java:168)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:184)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at com.owncloud.android.providers.DocumentsStorageProvider.openDocument(DocumentsStorageProvider.java:202)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.provider.DocumentsProvider.openAssetFile(DocumentsProvider.java:1344)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.content.ContentProvider$Transport.openAssetFile(ContentProvider.java:528)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:286)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.Binder.execTransactInternal(Binder.java:1165)
05-01 22:08:07.884 22332 23587 E DownloadFileRemoteOperation: 	at android.os.Binder.execTransact(Binder.java:1134)
05-01 22:08:07.884 22332 23587 E DocumentsStorageProvider: RemoteOperationResult(mSuccess=false, mHttpCode=-1, mHttpPhrase=null, mException=android.os.NetworkOnMainThreadException, mCode=HOST_NOT_AVAILABLE, message=null, getLogMessage=Unexpected exception)
```

**Comment by flocke** [comment]
> I've been using Nextcloud as a target for OpenGPG encrypted backups for ages on my old phone, with my new phone it stopped working: [nextcloud/android#4219](https://github.com/nextcloud/android/issues/4219)

It's a Nextcloud issue, but I added a workaround that should fix this. It will be in the next release (currently already in beta).

**Comment by nursoda** [comment]
I just tested the Backup process to a pre-selected Nextcloud folder with the current Google Play Beta. Since I set up "save a backup on every change" and I did some changes, I see several files in the target Nextcloud directory. However, doing a single "Backup→encrypted" from the main menu still results in a zero byte file!?

**Comment by flocke** [comment]
Yeah, that sometimes happens with Nextcloud. It seems like a bug in the client app, for which I opened an issue: https://github.com/nextcloud/android/issues/8201

**Comment by pschichtel** [comment]
> It's a Nextcloud issue, but I added a workaround that should fix this. It will be in the next release (currently already in beta).

they seem to have a different opinion: https://github.com/nextcloud/android/issues/8338#issuecomment-831757858
