### ISSUE TITLE
Crash on disabling tags 

### ISSUE THREAD

**Issue by ashjas** [andOTP/andOTP#857]
#### General information

* **App version:** 0.9.0
* **App source:** F-Droid
* **Android Version:** 11
* **Custom ROM:** ArrowOS

#### Expected result
**What is expected?** 
On filtering tags the app does not crash
**What does happen instead?**
I successfully restored aes backup on a new device.
By default all tags are enabled.
On switching off any of the tags, andotp crashes.

#### Logcat
```
06-20 12:26:16.792 16563 16563 D AndroidRuntime: Shutting down VM
06-20 12:26:16.793 16563 16563 E AndroidRuntime: FATAL EXCEPTION: main
06-20 12:26:16.793 16563 16563 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 16563
06-20 12:26:16.793 16563 16563 E AndroidRuntime: java.lang.UnsupportedOperationException
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at java.util.AbstractCollection.add(AbstractCollection.java:262)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at org.shadowice.flocke.andotp.Utilities.Settings.setTagToggle(Settings.java:532)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.MainActivity.lambda$setupDrawer$4$MainActivity(MainActivity.java:810)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.-$$Lambda$MainActivity$z9BOA7XJ4RBqCxbChF0dMpI28go.onClick(Unknown Source:2)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.view.View.performClick(View.java:7448)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7425)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.view.View.access$3600(View.java:810)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28305)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7665)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
06-20 12:26:16.793 16563 16563 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
06-20 12:26:16.797  1319 15318 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
06-20 12:26:16.797  1319  3341 W ActivityTaskManager:   Force finishing activity org.shadowice.flocke.andotp/.Activities.MainActivity
06-20 12:26:16.833  1319  3950 E FrameEvents: updateAcquireFence: Did not find frame.
06-20 12:26:16.841 16563 16563 I Process : Sending signal. PID: 16563 SIG: 9
06-20 12:26:16.875  1319  2166 I ActivityManager: Process org.shadowice.flocke.andotp (pid 16563) has died: fg  TOP
06-20 12:26:16.875  1319  1379 I WindowManager: WIN DEATH: Window{b73d9dc u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}
06-20 12:26:16.875  1319  1379 W InputDispatcher: Attempted to unregister already unregistered input channel 'b73d9dc org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity (server)'
06-20 12:26:16.878   737   737 I Zygote  : Process 16563 exited due to signal 9 (Killed)
06-20 12:26:16.909  1319  1636 W ActivityManager: setHasOverlayUi called on unknown pid: 16563
06-20 12:26:16.909  2788  2788 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1748 android.content.ContextWrapper.bindService:756 com.google.android.libraries.gsa.launcherclient.i.c:14 com.google.android.libraries.gsa.launcherclient.LauncherClient.reconnect:107 com.google.android.libraries.gsa.launcherclient.LauncherClient.onStart:67
06-20 12:26:16.910  1319  2166 W ActivityManager: Unable to start service Intent { act=com.android.launcher3.WINDOW_OVERLAY dat=app://com.android.launcher3:1000?v=9&cv=14 pkg=com.google.android.googlequicksearchbox } U=0: not found
06-20 12:26:16.914  1319  1697 I libprocessgroup: Successfully killed process cgroup uid 10243 pid 16563 in 37ms
06-20 12:26:17.301  1319  1636 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{155c50 u0 org.shadowice.flocke.andotp/.Activities.MainActivity t-1 f}}
```
#### Steps to reproduce

1.  Restore an aes backup on a new device.
2. By default all tags are enabled. Now try to disable any tag apart from "No tags"
3. Andotp crashes.

**Comment by ashjas** [comment]
supposedly duplicate of #856
