### ISSUE TITLE
New install, crash to white screen when going to Settings

### ISSUE THREAD

**Issue by xcelente** [andOTP/andOTP#873]
New install. Successful import. Going to Settings bombs out to a white screen, have to kill app.

GrapheneOS, Pixel 4a

**Comment by jsoberg** [comment]
Do you have a stack trace from logcat when this crash occurs?

**Comment by xcelente** [comment]
Where do I find that?

**Comment by Dwosky** [comment]
Hello,

I've encountered the same issue, using version 0.9.0.1-play in a new phone, new install. The weird thing is that on my old phone with the same version it works without issues... My guess is that I think I'm missing "something" in my new phone that its making the app crash. **Does andOTP have any dependency of any Google app/package that might not be in the ROM itself?** Author seems to be using GrapheneOS and I'm my case its MIUI, so it might not have all Google/Android packages by default.

Here is the exception I've been able to capture from logcat:
```
FATAL EXCEPTION: main
Process: org.shadowice.flocke.andotp, PID: 18117
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3539)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3699)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8057)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:262)
	at org.shadowice.flocke.andotp.Activities.SettingsActivity.onSharedPreferenceChanged(SettingsActivity.java:190)
	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
	at android.preference.Preference.tryCommit(Preference.java:1641)
	at android.preference.Preference.persistBoolean(Preference.java:1945)
	at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:89)
	at org.shadowice.flocke.andotp.Activities.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:469)
	at android.app.Fragment.performCreate(Fragment.java:2486)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2436)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2215)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2171)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2072)
	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3062)
	at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3009)
	at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184)
	at android.app.Activity.performCreate(Activity.java:8156)
	at android.app.Activity.performCreate(Activity.java:8115)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3512)
	... 11 more
```

**Comment by flocke** [comment]
andOTP does not have dependencies on any Google apps/components. The logcat indicates a problem with the SnackBar component from the libraries we are using on those phone. I will have to look into it some more.
