### ISSUE TITLE
Crash when MOTP secret is invalid

### ISSUE THREAD

**Issue by enwokoma** [andOTP/andOTP#875]
App crashes on Samsung S7 Edge when manually inputting an MOTP token with a wrong/invalid secret key...
Checked the logcat and this is what showed up in the logcat.

```
java.lang.NoSuchMethodError: No static method decodeHex(Ljava/lang/String;)[B in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.gigabytedevelopersinc.app.cometOTP.Database.Entry.validateSecret(Entry.java:628)
        at com.gigabytedevelopersinc.app.cometOTP.Dialogs.ManualEntryDialog.lambda$show$4(ManualEntryDialog.java:207)
```

**Comment by moritzgloeckl** [comment]
@enwokoma 

Do you remember which secret you entered? On my device it just says invalid secret and doesn't crash...
