### ISSUE TITLE
KeyStore error on MIUI 12.5.2.0

### ISSUE THREAD

**Issue by MagicLike** [andOTP/andOTP#879]
#### General information

* **App version:** 0.9.0.1-play
* **App source:** Google Play
* **Android Version:** 11 // MIUI 12.5.2.0.RGGEUXM (Stable Beta)
* **Custom ROM:** no
* **Device:** Xiaomi Redmi Note 8 Pro

#### Expected result
I open the app and unlock it with my fingerprint or with a pin / passwort
Then I can use the OTP keys

**What does happen instead?**
After an update to the MIUI Stable Beta 12.5.2.0, it shows me a message, that there is a KeyStore error and it can't load the encryption key from the KeyStore.
It also tells me, that I can go to the settings and change the database encryption.
When I try this, the app goes back to the start message.
I also tried to make a backup, but when i try it, the screen flashes white and the app crashes completely.

Similiar to #847, but I didn't transfered andOTP to a new device,
I also couldn't make a backup, so I haven't tried to wipe the data...

#### Logcat

https://gist.github.com/MagicLike/ecf9cc51bd2e59d92340f89f8db8eafe

#### Steps to reproduce
 
 * Update to the MIUI version 12.5.2.0
 * Open andOTP
 * Unlock it with the fingerprint
 * Try to change the encryption
 * Change the authenticate method, because the app says it's needed to change the encryption
 * Try again to change the encryption, this time it reminds to make an backup
 * Try to make an backup (app crashes)
 * Try to change the encryption without a backup
 * App goes back to the start message

**Comment by MarSoft** [comment]
Same issue here. I do have a backup but it is too old and hence incomplete...
Is there any additional information I could collect to help resolving the issue?

**Comment by flocke** [comment]
It seems like the MIUI update wiped or changed something in the KeyStore. Unfortunately the logcat from @MagicLike does not show any errors.

Maybe you could try to record another logcat @MarSoft ?

**Comment by MarSoft** [comment]
Same issue here. Is there any additional information I could collect to help fixing it?

**Comment by MarSoft** [comment]
@flocke, here is my logcat (with `-v color` option, best viewed in console or other compatible viewer). Launched app and got the error; then tried to switch encryption method (was redirected to main screen); then tried to export a backup (app crashed).
https://gist.github.com/a2741aa2ef733c388982c6450e29de17

**Comment by shenki** [comment]
I see a keystore error when running andTOP on Android 12:

```
11-12 09:31:16.623   469   469 E TrustyKeymaster: Response of size 4 contained error code -1000
11-12 09:31:16.623   469   469 E trusty_keymaster_hal: Cmd 12 returned error: -1000
11-12 09:31:16.623   466   598 E keystore2: keystore2::error: In KeystoreOperation::finish
11-12 09:31:16.623   466   598 E keystore2: 
11-12 09:31:16.623   466   598 E keystore2: Caused by:
11-12 09:31:16.623   466   598 E keystore2:     0: In finish: KeyMint::finish failed.
11-12 09:31:16.623   466   598 E keystore2:     1: Error::Km(ErrorCode(-1000))
11-12 09:31:16.624 13450 13450 W System.err: java.security.InvalidKeyException: Failed to unwrap key
11-12 09:31:16.624 13450 13450 W System.err: 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:792)
11-12 09:31:16.624 13450 13450 W System.err: 	at javax.crypto.Cipher.unwrap(Cipher.java:2440)
11-12 09:31:16.624 13450 13450 W System.err: 	at org.shadowice.flocke.andotp.Utilities.SecretKeyWrapper.unwrap(SecretKeyWrapper.java:80)
11-12 09:31:16.624 13450 13450 W System.err: 	at org.shadowice.flocke.andotp.Utilities.EncryptionHelper.loadOrGenerateWrappedKey(EncryptionHelper.java:255)
11-12 09:31:16.625 13450 13450 W System.err: 	at org.shadowice.flocke.andotp.Utilities.KeyStoreHelper.loadEncryptionKeyFromKeyStore(KeyStoreHelper.java:113)
11-12 09:31:16.625 13450 13450 W System.err: 	at org.shadowice.flocke.andotp.Activities.MainActivity.updateEncryption(MainActivity.java:582)
11-12 09:31:16.625 13450 13450 W System.err: 	at org.shadowice.flocke.andotp.Activities.MainActivity.onActivityResult(MainActivity.java:549)
```
```
11-12 09:31:16.625 13450 13450 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
11-12 09:31:16.625 13450 13450 W System.err: Caused by: javax.crypto.IllegalBlockSizeException
11-12 09:31:16.625 13450 13450 W System.err: 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:613)
11-12 09:31:16.625 13450 13450 W System.err: 	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineUnwrap(AndroidKeyStoreCipherSpiBase.java:790)
11-12 09:31:16.625 13450 13450 W System.err: 	... 21 more
11-12 09:31:16.625 13450 13450 W System.err: Caused by: android.security.KeyStoreException: Unknown error
11-12 09:31:16.625 13450 13450 W System.err: 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
11-12 09:31:16.625 13450 13450 W System.err: 	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java
```

**Comment by MagicLike** [comment]
First of all, sorry for not participating for so long.
Unfortunately I had to reinstall AndOTP because I need it in daily use. This time I set the encryption to password / pin and have had no problems so far.
Is there still anything I can do or help with?
