### ISSUE TITLE
Backup when using Android Work Profile

### ISSUE THREAD

**Issue by jakob-lundberg** [andOTP/andOTP#895]
#### General information

* **App version:** 0.9.0.1-play
* **App source:** Google Play
* **Android Version:** 11
* **Custom ROM:** No

#### Expected result
**What is expected?**
To be able to select backup location when using the app under the Work profile

**What does happen instead?**
The app craches
#### Logcat
```
10-14 10:55:35.061 21213 21213 E AndroidRuntime: FATAL EXCEPTION: main
10-14 10:55:35.061 21213 21213 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 21213
10-14 10:55:35.061 21213 21213 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc3 }
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2073)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1729)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5320)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5278)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity.requestBackupAccess(SettingsActivity.java:266)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity.access$400(SettingsActivity.java:70)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity$SettingsFragment.lambda$onCreate$3$SettingsActivity$SettingsFragment(SettingsActivity.java:443)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.-$$Lambda$SettingsActivity$SettingsFragment$0NTKDem2UEbvPbeB0Sb9RD0YFTk.onPreferenceClick(Unknown Source:2)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.preference.Preference.performClick(Preference.java:1165)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:260)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1212)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3204)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7698)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-14 10:55:35.061 21213 21213 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

#### Steps to reproduce
 
 * Install the app in the Work profile
 * Open settings and tap Default backup location

**Comment by flocke** [comment]
From the error message it looks like your work profile does not have a Documents Provider. There should one by default, in most cases it's an app called "Files" or "Documents". It won't work without one, since Android 11 a Documents Provider is required to access storage.
