### ISSUE TITLE
Touch Setting will be crash App!

### ISSUE THREAD

**Issue by LiuAlexanderII** [andOTP/andOTP#932]
Check if all requirements are fulfilled otherwise the issue will be closed without any comment

  * Check the [FAQ](https://github.com/andOTP/andOTP/wiki/Frequently-Asked-Questions) and search the [already reported issues](https://github.com/andOTP/andOTP/issues) before opening a new one!
  * Try again after clearing the apps data before posting (**don't forget to backup**)
  * Fill in **all** the details below
  * Record a logcat: https://goo.gl/mc71vk
  * Bug reports without logcat will be closed (I can not reproduce every bug myself and I can not fix them without logs)
  * Delete this entire info block

-----------------------------

#### General information

* **App version:**
* **App source:** Google Play / F-Droid / GitHub / ...
* **Android Version:**
* **Custom ROM:**

#### Expected result
**What is expected?** 

**What does happen instead?**

#### Logcat
```
Paste your logcat here (or use something like Pastbin for long logs)
```

#### Steps to reproduce
 
 * ...

**Comment by ziegenberg** [comment]
Hi @LiuAlexanderII 
Can you be a bit more specific about what exact steps you take and where the crash happens? In the current state, this issue can't be reproduced and it's difficult to give any advice or find the root cuase.

**Comment by samp1044** [comment]
Hello, I just experienced the same problem. The app crashes everytime I touch "settings". 

**App Version**
0.9.0.1-play
Date: 14.06.2021

**Device / Software**

SM-G998B  (Samsung Galaxy S21 Ultra)
Android 12  (One UI 4)
Safety Patch Level December 2021
Kernel Version: 5.4.129-22936777

**Exception captured with ADB**

`
2022-01-06 11:19:33.651 21930-21930/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.shadowice.flocke.andotp, PID: 21930
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4022)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8582)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
        at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:262)
        at org.shadowice.flocke.andotp.Activities.SettingsActivity.onSharedPreferenceChanged(SettingsActivity.java:190)
        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
        at android.preference.Preference.tryCommit(Preference.java:1766)
        at android.preference.Preference.persistBoolean(Preference.java:2070)
        at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:89)
        at org.shadowice.flocke.andotp.Activities.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:469)
        at android.app.Fragment.performCreate(Fragment.java:2486)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8262)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3996)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4188) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2425) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:226) 
        at android.os.Looper.loop(Looper.java:313) 
        at android.app.ActivityThread.main(ActivityThread.java:8582) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133) 
`

I additionally recorded the behavior (with a second device as the app prohibits screen recording and I can't change it) and uploaded it at: https://drive.google.com/file/d/1-mNusiBPudnrs3_QMST82WBpKqDiS1HM/view?usp=drivesdk 
Sorry for the device beeing set to german, I thought about that too late.

**Comment by irgendwie** [comment]
Experiencing the same issue with Google Pixel 6 and **GrapheneOS**. This issue seems to be a duplicate of #873.
Whenever I click on 'Settings', the crash occurs and I'm left with a white screen.

App version:
0.9.0.1 (F-Droid Store)

Logcat:
```
--------- beginning of crash
05-04 10:25:22.344 16198 16198 E AndroidRuntime: FATAL EXCEPTION: main
05-04 10:25:22.344 16198 16198 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 16198
05-04 10:25:22.344 16198 16198 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.SettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at com.android.internal.os.ExecInit.main(ExecInit.java:48)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
05-04 10:25:22.344 16198 16198 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at com.google.android.material.snackbar.Snackbar.make(Snackbar.java:262)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity.onSharedPreferenceChanged(SettingsActivity.java:190)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.preference.Preference.tryCommit(Preference.java:1621)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.preference.Preference.persistBoolean(Preference.java:1925)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.preference.TwoStatePreference.setChecked(TwoStatePreference.java:89)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity$SettingsFragment.onCreate(SettingsActivity.java:469)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.Fragment.performCreate(Fragment.java:2486)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3057)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:185)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8073)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8045)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        ... 14 more
05-04 10:25:22.344 16198 16228 E BpDisplayEventConnection: Failed to transact (-9)
05-04 10:25:22.344 16198 16198 E AndroidRuntime: Error reporting crash
05-04 10:25:22.344 16198 16198 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:571)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at android.app.IActivityManager$Stub$Proxy.handleApplicationCrash(IActivityManager.java:5351)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:156)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
05-04 10:25:22.344 16198 16198 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2200)
05-04 10:25:22.344 16198 16198 I Process : Sending signal. PID: 16198 SIG: 9
```
