### ISSUE TITLE
CRASH on backup / backup location selection

### ISSUE THREAD

**Issue by fda77** [andOTP/andOTP#948]
CRASH on backup / backup location selection

#### General information

* **App version:** latest 0.9.0.1
* **App source:** Google Store
* **Android Version:** 11
* **Custom ROM:** Lineage, latest

#### Expected result
no crash

**What does happen instead?**
crash

#### Logcat
```
01-25 13:01:23.156   994  1642 I ActivityTaskManager: START u0 {act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc3} from uid 10158
01-25 13:01:23.159  9501  9501 D AndroidRuntime: Shutting down VM
01-25 13:01:23.174  9501  9501 E AndroidRuntime: FATAL EXCEPTION: main
01-25 13:01:23.174  9501  9501 E AndroidRuntime: Process: org.shadowice.flocke.andotp, PID: 9501

01-25 13:01:23.174  9501  9501 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0xc3 }
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2067)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1727)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5314)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5272)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity.requestBackupAccess(SettingsActivity.java:266)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity.access$400(SettingsActivity.java:70)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.SettingsActivity$SettingsFragment.lambda$onCreate$3$SettingsActivity$SettingsFragment(SettingsActivity.java:443)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at org.shadowice.flocke.andotp.Activities.-$$Lambda$SettingsActivity$SettingsFragment$0NTKDem2UEbvPbeB0Sb9RD0YFTk.onPreferenceClick(Unknown Source:2)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.preference.Preference.performClick(Preference.java:1165)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:260)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.widget.AbsListView.performItemClick(AbsListView.java:1187)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3179)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.widget.AbsListView$3.run(AbsListView.java:4097)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7664)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
01-25 13:01:23.174  9501  9501 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
01-25 13:01:23.185   994  1642 W ActivityTaskManager:   Force finishing activity org.shadowice.flocke.andotp/.Activities.SettingsActivity

01-25 13:01:23.230  9501  9501 I Process : Sending signal. PID: 9501 SIG: 9
01-25 13:01:23.257   994  9915 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
01-25 13:01:23.272   994  1175 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
01-25 13:01:23.272   994  1175 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
01-25 13:01:23.331   994  8038 I WindowManager: WIN DEATH: Window{da25bcd u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.SettingsActivity}
01-25 13:01:23.332   994  4195 I ActivityManager: Process org.shadowice.flocke.andotp (pid 9501) has died: fg  TOP
01-25 13:01:23.335     0     0 I binder  : undelivered TRANSACTION_COMPLETE
01-25 13:01:23.335     0     0 I binder  : undelivered transaction 250312, process died.
01-25 13:01:23.338   994  1469 W Looper  : Ignoring unexpected epoll events 0x19 on fd 232 that is no longer registered.
01-25 13:01:23.354   994  2406 I WindowManager: WIN DEATH: Window{6066ca u0 org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity}
01-25 13:01:23.354   994  2406 W InputDispatcher: Attempted to unregister already unregistered input channel '6066ca org.shadowice.flocke.andotp/org.shadowice.flocke.andotp.Activities.MainActivity (server)'
01-25 13:01:23.369   396   396 I Zygote  : Process 9501 exited due to signal 9 (Killed)

```

#### Steps to reproduce
 - in settings
 - tap default backup location
 
Also crashes when
 - open Hamburger
 - tap Backup

**Comment by fda77** [comment]
Installing https://www.apkmirror.com/apk/lineageos/files-lineageos/ prevents the crash

**Comment by fda77** [comment]
So a backup now works and the content of an unencrypted file looking good.
But restoring does not work: After selecting the just created backup, the spinner at the bottom of settings view never disappears. There is not much in log:

```
01-25 21:26:11.020   720  3490 W ActivityManager: Slow operation: 76ms so far, now at getContentProviderImpl: after updateOomAdj
01-25 21:26:11.020   720  3490 W ActivityManager: Slow operation: 77ms so far, now at getContentProviderImpl: done!
01-25 21:26:04.685 14678 14678 E oid.documentsu: No package ID ff found for ID 0xffffffff.
01-25 21:26:11.126 16771 16792 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
01-25 21:26:11.181  1789  1802 I droid.launcher: NativeAlloc concurrent copying GC freed 11196(630KB) AllocSpace objects, 0(0B) LOS objects, 70% free, 2617KB/8761KB, paused 244us total 175.231ms
01-25 21:26:11.192  1789  1804 W System  : A resource failed to call release.
01-25 21:26:11.193  1789  1804 I chatty  : uid=10113(com.android.launcher3) FinalizerDaemon identical 1 line
01-25 21:26:11.193  1789  1804 W System  : A resource failed to call release.
01-25 21:26:11.315  1568  1587 I ndroid.systemu: NativeAlloc concurrent copying GC freed 10548(475KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 7218KB/14MB, paused 183us total 300.537ms

```
